name: auto-commit

on:
  workflow_run:
    workflows:
      - panvimdoc
    types:
      - completed

jobs:
  commit:
    runs-on: ubuntu-latest
    name: auto commit
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: vimdoc
          path: doc/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
