name: ci-auto-commit

on:
  push:
    branches:
      - main

jobs:
  panvimdoc:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: im-switch.nvim
      - uses: actions/upload-artifact@v4
        with:
          name: vimdoc
          path: doc/

  auto-commit:
    runs-on: ubuntu-latest
    name: auto commit
    needs:
      - panvimdoc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: vimdoc
          path: doc/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
