name: panvimdoc

on:
  push:
    branches:
      - main

jobs:
  panvimdoc:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: im-switch.nvim
      - uses: actions/upload-artifact@v4
        with:
          name: vimdoc
          path: doc/
