name: test

on:
  push:
    branches: [main, feature/*]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Run unit tests
        run: |
          nvim --headless -u tests/lua/minimal_init.lua -c "PlenaryBustedDirectory tests/lua"
